package practise;

import org.testng.annotations.Test;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;


public class GetReq {
	
	@Test
	public void getData() 
	{
		RestAssured.baseURI="https://ws.testsrv.numberportability.ch/inetref/api";
		//RestAssured.authentication=RestAssured.basic("admin","d-J+lC2Hk7A");
		
		
		RequestSpecification req = RestAssured.given().cookie("access_token", "eyJ4NXQjUzI1NiI6IktXb2Z6Rk9OT2dNemY4aS1vcllycEVJTXFOaDBqOGZqcVp3bG8yRGgyMjQiLCJraWQiOiJpbmV0dWFhIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJBZkppSyIsInRzcF9pZCI6OTgwOTUsInVzZXJfdHlwZSI6IlciLCJ1c2VyX25hbWUiOiJBZkppSyIsInNjb3BlIjpbIm9wZW5pZCBwcm9maWxlIGVtYWlsIl0sImlzcyI6ImluZXQtdWFhIiwic2Vzc2lvbl9pZCI6IkFmSmlLIiwiZXhwIjoxNzcyNzQxOTg0LCJpYXQiOjE3NzI2OTg3ODQsImp0aSI6IjZmNWE5NmQ0LWZhMGYtNDI5OS1hZjExLTE5NTk2NzIzOGQ3MyIsImNsaWVudF9pZCI6IndlYl9hcHAiLCJhdXRob3JpdGllcyI6WyJST0xFX0lfUiIsIlJPTEVfRF9XIiwiUk9MRV9TX1IiLCJST0xFX1BfVyIsIlJPTEVfV0VCX1NFUlZJQ0UiLCJST0xFX09fVyIsIlJPTEVfVF9SIiwiUk9MRV9PX1IiLCJST0xFX0lfVyIsIlJPTEVfUF9SIiwiUk9MRV9XX1ciLCJST0xFX1dfUiIsIlJPTEVfVF9XIiwiUk9MRV9VU0VSIiwiUk9MRV9DX1IiLCJST0xFX0RfUiJdfQ.LGmWJlRQdPDnFpkoKQ8_TZ2GDLFDNY-738YbNThrblDDrJNO2gsh1tc7JJNxMUYsPQm1eKckCh-FlSqpJ4z9r4gXuTDeoa4Y9vGj-vCVTVTu1jTxz0SBrjyObiWDU0w2Xpfb-UI1i20H6WposxyZYew-fdEFSS0aN2OrCvHTGPuZTjYZp-8hpSFhh1FRIdFjSyJyffPxAWCC_i8hNNgrl7_wRMhueXCOxNEBjPDHzp32cQyRDo4WTt475FeFFXyojq5agIWPP5nLNdGGAI5SLIRqCH_PWjrnOVD-MEy9fKcjRsuFpd33ESWF6FJgqASaJcjuWUoz1ogFcc098RKq9g; session_token=eyJ4NXQjUzI1NiI6IktXb2Z6Rk9OT2dNemY4aS1vcllycEVJTXFOaDBqOGZqcVp3bG8yRGgyMjQiLCJraWQiOiJpbmV0dWFhIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJBZkppSyIsInRzcF9pZCI6OTgwOTUsInVzZXJfdHlwZSI6IlciLCJ1c2VyX25hbWUiOiJBZkppSyIsInNjb3BlIjpbIm9wZW5pZCBwcm9maWxlIGVtYWlsIl0sImlzcyI6ImluZXQtdWFhIiwic2Vzc2lvbl9pZCI6IkFmSmlLIiwiZXhwIjoxNzczMzAzNTg0LCJpYXQiOjE3NzI2OTg3ODQsImp0aSI6Ijk1ZWE0Y2NhLWJhZGYtNDBiOC1hM2NlLTdiYWZiNjNhZmVmNSIsImNsaWVudF9pZCI6IndlYl9hcHAiLCJhdXRob3JpdGllcyI6WyJST0xFX0lfUiIsIlJPTEVfRF9XIiwiUk9MRV9TX1IiLCJST0xFX1BfVyIsIlJPTEVfV0VCX1NFUlZJQ0UiLCJST0xFX09fVyIsIlJPTEVfVF9SIiwiUk9MRV9PX1IiLCJST0xFX0lfVyIsIlJPTEVfUF9SIiwiUk9MRV9XX1ciLCJST0xFX1dfUiIsIlJPTEVfVF9XIiwiUk9MRV9VU0VSIiwiUk9MRV9DX1IiLCJST0xFX0RfUiJdfQ.ZIhId8pjvanN2D-gP6WPj7mSGipe-wKAoX_4mbtoWZbhDAB5Uq2Nkf1EsnAfGZn28BkvjM4vys6C-DfV29TzXXG_bbFBtAvRDY4PfX6twtsPcPRbNgRf2RAHgxtBdL4z3vbkaOYMan92BrqyB2KqF2lHuV59iSNvixtzFXDqsDmz7mE5kt3ysYKuOdwzpc_vCy8csE-EmUmbl4xo0Itw7bThRNOK-ulXKAmmq9u4BQgwemjM4sn5Ph2kBupvGNXftWEAQonZ0gU4fgDXykT8dRHwwiFQmYAXGflDHjrHAsSgFdKmsCXXs5acjIeDtk25Dv1GeLwoD9yCz0gTmxrL_A")
				.contentType("application/json").
		when().body("");
		
		Response resp = req.get("/telecom-service-provider");
		//resp.print();
		//System.out.println(resp); Print Memory 
		resp.prettyPrint();
	}

}
